//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mug.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Layout() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mug.Common.Resources.Layout", typeof(Layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 About Us 的當地語系化字串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Adderss 的當地語系化字串。
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Comapny_desc 的當地語系化字串。
        /// </summary>
        public static string Comapny_desc {
            get {
                return ResourceManager.GetString("Comapny_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Company 的當地語系化字串。
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Contact Us 的當地語系化字串。
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 2F., No. 55, Yongfu St., Wanhua Dist., Taipei City 108, Taiwan (R.O.C.) 的當地語系化字串。
        /// </summary>
        public static string Contact_Addr {
            get {
                return ResourceManager.GetString("Contact_Addr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Send 的當地語系化字串。
        /// </summary>
        public static string Contact_Btn {
            get {
                return ResourceManager.GetString("Contact_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Your Email (Require) 的當地語系化字串。
        /// </summary>
        public static string Contact_Email {
            get {
                return ResourceManager.GetString("Contact_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Memo 的當地語系化字串。
        /// </summary>
        public static string Contact_Memo {
            get {
                return ResourceManager.GetString("Contact_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Your Name (Require) 的當地語系化字串。
        /// </summary>
        public static string Contact_Name {
            get {
                return ResourceManager.GetString("Contact_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order Inquiry 的當地語系化字串。
        /// </summary>
        public static string Contact_opt1 {
            get {
                return ResourceManager.GetString("Contact_opt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Product Inquiry 的當地語系化字串。
        /// </summary>
        public static string Contact_opt2 {
            get {
                return ResourceManager.GetString("Contact_opt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delivery Order 的當地語系化字串。
        /// </summary>
        public static string Contact_opt3 {
            get {
                return ResourceManager.GetString("Contact_opt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Else Service 的當地語系化字串。
        /// </summary>
        public static string Contact_opt4 {
            get {
                return ResourceManager.GetString("Contact_opt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Tel 的當地語系化字串。
        /// </summary>
        public static string Contact_Tel {
            get {
                return ResourceManager.GetString("Contact_Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Email 的當地語系化字串。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Exhibition 的當地語系化字串。
        /// </summary>
        public static string Exhibition {
            get {
                return ResourceManager.GetString("Exhibition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Exhibition Description(未打) 的當地語系化字串。
        /// </summary>
        public static string Exhibition_Description {
            get {
                return ResourceManager.GetString("Exhibition_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Our Factory 的當地語系化字串。
        /// </summary>
        public static string Factory {
            get {
                return ResourceManager.GetString("Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Chao&apos;an, Chaozhou, GuangdongChina 的當地語系化字串。
        /// </summary>
        public static string Factory_Addr {
            get {
                return ResourceManager.GetString("Factory_Addr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Souvenirs Comapny. 的當地語系化字串。
        /// </summary>
        public static string FooterCompany {
            get {
                return ResourceManager.GetString("FooterCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Home 的當地語系化字串。
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Language 的當地語系化字串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Menu 的當地語系化字串。
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Product 的當地語系化字串。
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Ceramics 的當地語系化字串。
        /// </summary>
        public static string Product_Ceramics {
            get {
                return ResourceManager.GetString("Product_Ceramics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Glass 的當地語系化字串。
        /// </summary>
        public static string Product_Glass {
            get {
                return ResourceManager.GetString("Product_Glass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Mug 的當地語系化字串。
        /// </summary>
        public static string Product_Mug {
            get {
                return ResourceManager.GetString("Product_Mug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Decoration 的當地語系化字串。
        /// </summary>
        public static string Product_Other {
            get {
                return ResourceManager.GetString("Product_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Product Consultation 的當地語系化字串。
        /// </summary>
        public static string Require {
            get {
                return ResourceManager.GetString("Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Require_Description(未打) 的當地語系化字串。
        /// </summary>
        public static string Require_Description {
            get {
                return ResourceManager.GetString("Require_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Service Items 的當地語系化字串。
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Service_Description(未打) 的當地語系化字串。
        /// </summary>
        public static string Service_Description {
            get {
                return ResourceManager.GetString("Service_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Experience Evaluation 的當地語系化字串。
        /// </summary>
        public static string Step1 {
            get {
                return ResourceManager.GetString("Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Step1Text {
            get {
                return ResourceManager.GetString("Step1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Third Party Inspection 的當地語系化字串。
        /// </summary>
        public static string Step2 {
            get {
                return ResourceManager.GetString("Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Step2Text {
            get {
                return ResourceManager.GetString("Step2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 High Quality 的當地語系化字串。
        /// </summary>
        public static string Step3 {
            get {
                return ResourceManager.GetString("Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Step3Text {
            get {
                return ResourceManager.GetString("Step3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Step4(未打) 的當地語系化字串。
        /// </summary>
        public static string Step4 {
            get {
                return ResourceManager.GetString("Step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Tel 的當地語系化字串。
        /// </summary>
        public static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 View our Factory 的當地語系化字串。
        /// </summary>
        public static string VideoTxt {
            get {
                return ResourceManager.GetString("VideoTxt", resourceCulture);
            }
        }
    }
}
