//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mug.Dao
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MugFactoryEntities : DbContext
    {
        public MugFactoryEntities()
            : base("name=MugFactoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AboutPage> AboutPage { get; set; }
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<Blogger> Blogger { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<HomePage> HomePage { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<ProductPage> ProductPage { get; set; }
        public virtual DbSet<SerialNumber> SerialNumber { get; set; }
    }
}
